"""SQLite persistence layer for the BTCUSDT signal engine (Phase 3).

Exposes the persistent source of truth for signals plus the schema needed by
later phases (demo accounts, positions, trades). No execution/trading logic
lives here.
"""

from .database import (
    CANDLE_LOG_RETENTION,
    DECIMAL_COLUMNS,
    DEFAULT_DB_PATH,
    CandleLogEntry,
    CandleLogRepository,
    ConfigRepository,
    Database,
    DemoDuplicateError,
    DemoError,
    DemoNotFoundError,
    DemoRepository,
    DemoValidationError,
    RuntimeStateRepository,
    SchedulerStateRepository,
    SignalRepository,
    iso_utc_now,
    to_decimal,
    to_decimal_signed,
    validate_signal_prices,
)
from .models import (
    ACTIVE_STATUSES,
    ALLOWED_TRANSITIONS,
    DIRECTION_LONG,
    DIRECTION_SHORT,
    DIRECTIONS,
    PRICE_ORDERING,
    STATUS_CANCELLED,
    STATUS_OPEN,
    STATUS_PENDING_ENTRY,
    STATUS_SL_HIT,
    STATUS_TP_HIT,
    STATUSES,
    TERMINAL_STATUSES,
    InvalidTransitionError,
    Signal,
    SignalError,
    SignalExistsError,
    SignalNotFoundError,
    SignalValidationError,
)

__all__ = [
    "ACTIVE_STATUSES",
    "ALLOWED_TRANSITIONS",
    "CANDLE_LOG_RETENTION",
    "DEFAULT_DB_PATH",
    "DECIMAL_COLUMNS",
    "DIRECTIONS",
    "DIRECTION_LONG",
    "DIRECTION_SHORT",
    "CandleLogEntry",
    "CandleLogRepository",
    "ConfigRepository",
    "Database",
    "DemoDuplicateError",
    "DemoError",
    "DemoNotFoundError",
    "DemoRepository",
    "DemoValidationError",
    "InvalidTransitionError",
    "PRICE_ORDERING",
    "RuntimeStateRepository",
    "STATUS_CANCELLED",
    "STATUS_OPEN",
    "STATUS_PENDING_ENTRY",
    "STATUS_SL_HIT",
    "STATUS_TP_HIT",
    "STATUSES",
    "SchedulerStateRepository",
    "Signal",
    "SignalError",
    "SignalExistsError",
    "SignalNotFoundError",
    "SignalRepository",
    "SignalValidationError",
    "TERMINAL_STATUSES",
    "iso_utc_now",
    "to_decimal",
    "to_decimal_signed",
    "validate_signal_prices",
]
