"""BTCUSDT AI signal engine.

Phase 4: LLM provider configuration.
Phase 5: LLM analysis of the closed-candle context (context + strict
LONG/SHORT/WAIT structured output).
Phase 6: Signal Engine — the authoritative validation/persistence boundary
between the Phase 5 in-memory analysis and SQLite (one OPEN signal, Decimals,
fail-safe errors, AI lock).
Phase 7: TP/SL Monitor — independent observer of 1m closed candles that closes
the OPEN signal at its configured exit; never analyzes, never modifies TP/SL.
Phase 9: Restart Recovery — read-only startup pass over SQLite that recovers
the current OPEN signal (if any) so monitoring resumes; never calls AI,
never fetches market data, never creates/updates signals.
Phase 10: 1H Scheduler — decides when the AI may analyze a closed 1H candle
(at most once per candle, only while no PENDING_ENTRY/OPEN signal exists);
independent from the TP/SL monitor.
Phase 11: Telegram Notifications — an optional read-only outbound adapter that
announces new PENDING_ENTRY signals, position opens, TP/SL closes, and
ambiguous candles only after their SQLite state transitions have committed.
"""

from .analysis import (
    CONFIDENCE_MAX,
    CONFIDENCE_MIN,
    DECISIONS,
    SignalAnalysis,
    SignalAnalysisError,
    SignalAnalyzer,
    SignalDecision,
    SignalDecisionModel,
    analyze_signal,
    build_prompt,
)
from .config import (
    ConfigService,
    SecretStore,
    SettingsError,
    SettingsLockedError,
    SettingsTestError,
    SettingsValidationError,
    mask_secret,
)
from .context import (
    DEFAULT_MAX_CANDLES,
    SNAPSHOT_COLUMNS,
    AnalysisContext,
    AnalysisContextError,
    build_analysis_context,
)
from .engine import SignalEngine, SignalEngineResult, SignalOutcome
from .llm import (
    DEFAULT_MODEL,
    DEFAULT_PROVIDER,
    ENV_LLM_BASE_URL,
    ENV_LLM_MAX_RETRIES,
    ENV_LLM_MAX_TOKENS,
    ENV_LLM_MODEL,
    ENV_LLM_PROVIDER,
    ENV_LLM_TEMPERATURE,
    ENV_LLM_TIMEOUT,
    KNOWN_MODEL_KEYS,
    PROVIDER_DEFAULT_MODEL,
    SIGNAL_MODELS,
    LLMConfig,
    LLMConfigError,
    ModelSpec,
    build_llm_client,
    get_model_spec,
    llm_config_from_env,
    validate_llm_config,
)
from .monitor import (
    CLOSE_REASON_SL,
    CLOSE_REASON_TP,
    DEFAULT_CANDLE_LIMIT,
    MONITOR_INTERVAL,
    MonitorOutcome,
    MonitorResult,
    SignalMonitor,
    evaluate_candle,
    evaluate_entry,
)
from .multiagent import (
    ENV_ANALYSIS_MODE,
    MULTI_AGENT_MODE,
    SINGLE_AGENT_MODE,
    MultiAgentSignalAnalyzer,
    resolve_analysis_mode,
)
from .recovery import RecoveryOutcome, RecoveryResult, RecoveryService
from .scheduler import (
    DEFAULT_DETECTION_LIMIT,
    DEFAULT_POLL_INTERVAL,
    DEFAULT_WINDOW_CANDLES,
    SCHEDULER_INTERVAL,
    OneHourScheduler,
    SchedulerOutcome,
    SchedulerResult,
)
from .state import SignalState
from .telegram import (
    DEFAULT_BACKOFF_SECONDS,
    DEFAULT_MAX_RETRIES,
    DEFAULT_TIMEOUT_SECONDS,
    ENV_TELEGRAM_BACKOFF,
    ENV_TELEGRAM_BOT_TOKEN,
    ENV_TELEGRAM_CHAT_ID,
    ENV_TELEGRAM_ENABLED,
    ENV_TELEGRAM_MAX_RETRIES,
    ENV_TELEGRAM_TIMEOUT,
    MAX_MESSAGE_CHARS,
    RefreshableTelegramNotifier,
    TelegramClient,
    TelegramConfig,
    TelegramConfigError,
    TelegramError,
    TelegramNotifier,
    TelegramSendResult,
    format_epoch_ms,
    format_price,
    format_signal_ambiguous,
    format_signal_created,
    format_signal_opened,
    format_signal_sl,
    format_signal_tp,
    format_timestamp,
    telegram_config_from_env,
    telegram_notifier_from_env,
    validate_telegram_config,
)
from .validator import (
    SignalCandidate,
    to_price,
    validate_analysis,
    validate_confidence,
    validate_decision,
)

__all__ = [
    "CONFIDENCE_MAX",
    "CONFIDENCE_MIN",
    "DECISIONS",
    "DEFAULT_MAX_CANDLES",
    "SNAPSHOT_COLUMNS",
    "AnalysisContext",
    "AnalysisContextError",
    "ConfigService",
    "SecretStore",
    "SettingsError",
    "SettingsLockedError",
    "SettingsTestError",
    "SettingsValidationError",
    "mask_secret",
    "SignalAnalysis",
    "SignalAnalysisError",
    "SignalAnalyzer",
    "SignalCandidate",
    "SignalDecision",
    "SignalDecisionModel",
    "SignalEngine",
    "SignalEngineResult",
    "SignalOutcome",
    "SignalState",
    "SignalMonitor",
    "MonitorOutcome",
    "MonitorResult",
    "evaluate_candle",
    "evaluate_entry",
    "RecoveryOutcome",
    "RecoveryResult",
    "RecoveryService",
    "MONITOR_INTERVAL",
    "OneHourScheduler",
    "SCHEDULER_INTERVAL",
    "SchedulerOutcome",
    "SchedulerResult",
    "DEFAULT_DETECTION_LIMIT",
    "DEFAULT_POLL_INTERVAL",
    "DEFAULT_WINDOW_CANDLES",
    "CLOSE_REASON_TP",
    "CLOSE_REASON_SL",
    "ENV_ANALYSIS_MODE",
    "MULTI_AGENT_MODE",
    "SINGLE_AGENT_MODE",
    "MultiAgentSignalAnalyzer",
    "resolve_analysis_mode",
    "analyze_signal",
    "build_analysis_context",
    "build_prompt",
    "to_price",
    "validate_analysis",
    "validate_confidence",
    "validate_decision",
    "DEFAULT_MODEL",
    "DEFAULT_PROVIDER",
    "DEFAULT_CANDLE_LIMIT",
    "DEFAULT_BACKOFF_SECONDS",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_TIMEOUT_SECONDS",
    "ENV_LLM_BASE_URL",
    "ENV_LLM_MAX_RETRIES",
    "ENV_LLM_MAX_TOKENS",
    "ENV_LLM_MODEL",
    "ENV_LLM_PROVIDER",
    "ENV_LLM_TEMPERATURE",
    "ENV_LLM_TIMEOUT",
    "ENV_TELEGRAM_BACKOFF",
    "ENV_TELEGRAM_BOT_TOKEN",
    "ENV_TELEGRAM_CHAT_ID",
    "ENV_TELEGRAM_ENABLED",
    "ENV_TELEGRAM_MAX_RETRIES",
    "ENV_TELEGRAM_TIMEOUT",
    "MAX_MESSAGE_CHARS",
    "RefreshableTelegramNotifier",
    "TelegramClient",
    "TelegramConfig",
    "TelegramConfigError",
    "TelegramError",
    "TelegramNotifier",
    "TelegramSendResult",
    "format_epoch_ms",
    "format_price",
    "format_signal_ambiguous",
    "format_signal_created",
    "format_signal_opened",
    "format_signal_sl",
    "format_signal_tp",
    "format_timestamp",
    "telegram_config_from_env",
    "telegram_notifier_from_env",
    "validate_telegram_config",
    "KNOWN_MODEL_KEYS",
    "LLMConfig",
    "LLMConfigError",
    "ModelSpec",
    "PROVIDER_DEFAULT_MODEL",
    "SIGNAL_MODELS",
    "build_llm_client",
    "get_model_spec",
    "llm_config_from_env",
    "validate_llm_config",
]
